// `j2 cluster up|down [--name <n>]` (ADR-0009, amended): j2 OWNS kind cluster creation because
// the one thing a Sandbox data plane cannot get after the fact is the repos mount — kind's
// hostPath resolves against the NODE (the kind Docker container), so `<instance>/repos` reaches
// Sandbox pods only via `nodes[].extraMounts` baked in AT CLUSTER CREATION. `up` therefore
// generates the kind config (repos → /repos, read-only), creates the cluster, and installs the
// bundled Sandbox CRD; a cluster that already exists is left alone LOUDLY (its mounts may be
// stale — recreating is the only fix, and that is the user's call). The operator itself still
// runs out-of-band (`just operator-run`) until a deployable operator image lands.
//
// The process seam is injectable (like the orchestrator's kubectl port) so the command logic is
// unit-testable without kind/docker; the real path is the kind e2e tier's job.

import { execFile } from "node:child_process";
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
import { parseArgs } from "node:util";
import { resolveRoot } from "../instance.ts";
import { activity, result, type Io } from "../output.ts";

/** Run one external command to completion (kind / kubectl). Injectable for tests. */
export type CmdExec = (cmd: string, args: string[]) => Promise<{ stdout: string }>;

/** The Sandbox CRD bundled with the CLI (synced from operator/config/crd/bases). */
const CRD_PATH = fileURLToPath(new URL("../../assets/sandbox-crd.yaml", import.meta.url));

export async function cluster(args: string[], io: Io, exec: CmdExec = defaultExec): Promise<number> {
  const { values, positionals } = parseArgs({
    args,
    allowPositionals: true,
    strict: false,
    options: { name: { type: "string" } },
  });
  const sub = positionals[0];
  const name = (values.name as string | undefined) ?? "j2";

  if (sub === "up") return up(name, io, exec);
  if (sub === "down") {
    await exec("kind", ["delete", "cluster", "--name", name]);
    activity(io, `deleted kind cluster "${name}"`);
    result(io, { cluster: name, deleted: true });
    return 0;
  }
  activity(io, "usage: j2 cluster up|down [--name <n>]");
  return 2;
}

async function up(name: string, io: Io, exec: CmdExec): Promise<number> {
  const root = resolveRoot(io.cwd);
  const reposDir = join(root, "repos");
  await mkdir(reposDir, { recursive: true });
  await mkdir(join(root, ".j2"), { recursive: true });

  const configPath = join(root, ".j2", "kind.yaml");
  await writeFile(configPath, kindConfig(name, reposDir));

  const existing = (await exec("kind", ["get", "clusters"])).stdout.split("\n").map((l) => l.trim());
  if (existing.includes(name)) {
    activity(io, `kind cluster "${name}" already exists — leaving it as-is.`);
    activity(io, `  NOTE: extraMounts are baked at creation; if repos/ moved, \`j2 cluster down\` and re-up.`);
  } else {
    activity(io, `creating kind cluster "${name}" (repos/ mounted read-only at /repos on the node)…`);
    await exec("kind", ["create", "cluster", "--name", name, "--config", configPath]);
  }

  activity(io, "installing the Sandbox CRD…");
  await exec("kubectl", ["apply", "--context", `kind-${name}`, "-f", CRD_PATH]);

  activity(io, "cluster ready. next steps:");
  activity(io, "  1. run the Sandbox operator against it (repo dev: `just operator-run`)");
  activity(io, "  2. set `sandbox: { image: … }` in j2.config.ts, then `j2 dev`");
  result(io, { cluster: name, context: `kind-${name}`, repos: reposDir, crd: "sandboxes.core.j2.dev" });
  return 0;
}

/** The generated kind config: the ONE thing that must exist at creation time (see header). */
export function kindConfig(name: string, reposDir: string): string {
  return `# Generated by \`j2 cluster up\` — do not edit; regenerate by re-running it.
kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: ${name}
nodes:
  - role: control-plane
    extraMounts:
      # The instance's repos/ (RO default/ checkouts) exposed to the NODE, so Sandbox pods can
      # hostPath-mount it (ADR-0004 storage shape). Baked here because kind cannot add mounts
      # to a live cluster.
      - hostPath: ${reposDir}
        containerPath: /repos
        readOnly: true
`;
}

const defaultExec: CmdExec = (cmd, args) =>
  new Promise((resolve, reject) => {
    execFile(cmd, args, { maxBuffer: 8 * 1024 * 1024 }, (err, stdout, stderr) => {
      if (err) {
        const hint =
          (err as NodeJS.ErrnoException).code === "ENOENT"
            ? `\`${cmd}\` is not installed or not on PATH` + (cmd === "kind" ? " (brew install kind)" : "")
            : stderr || err.message;
        reject(new Error(`${cmd} ${args[0]} failed: ${hint}`));
      } else resolve({ stdout });
    });
  });
