---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.j2.dev
  resources:
  - repos
  verbs:
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.j2.dev
  resources:
  - repos/status
  - sandboxes/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - core.j2.dev
  resources:
  - sandboxes
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.j2.dev
  resources:
  - sandboxes/finalizers
  verbs:
  - update
