// The instance-image build seam (ADR-0019): `j2 up` builds ONE image — engine + this instance's
// workflows baked (ADR-0008) — staleness-checked by a content hash over the instance's sources.
// `BuildPort` is what the converge logic drives (tests fake it); `pnpmDockerBuild` is the real one:
// `pnpm deploy` materializes the instance package (workspace deps resolved — the kit-dev path;
// published instances resolve the same way from the registry), then a generated Dockerfile bakes
// the bundle onto node:24 with git (the in-cluster repos reconcile clones with it, ADR-0004/0019).

import { createHash } from "node:crypto";
import { execFile } from "node:child_process";
import { mkdtemp, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join, relative } from "node:path";
import { promisify } from "node:util";

const exec = promisify(execFile);

export type BuildPort = {
  /** Materialize the instance package (+ resolved deps) into `outDir` (`pnpm deploy`). */
  bundle(instanceDir: string, outDir: string): Promise<void>;
  /** `docker build` the bundle dir (its Dockerfile is generated by the caller). */
  build(tag: string, contextDir: string): Promise<void>;
  /** `docker push` — the registry delivery (ADR-0019). */
  push(tag: string): Promise<void>;
  /** `kind load docker-image` — the no-registry delivery onto a kind cluster's nodes. */
  kindLoad(tag: string, cluster: string): Promise<void>;
};

/** Paths that never affect the deployed image (state, deps, VCS, secrets). */
const HASH_EXCLUDE = new Set([".j2", "node_modules", ".git", ".env"]);

/**
 * A short content hash over every file in the instance folder (sorted walk, minus excluded paths)
 * plus the kit version — the staleness key `j2 up` stamps on the Deployment. Any source edit or a
 * kit upgrade changes it; a re-run with neither skips the whole build layer.
 */
export async function contentHash(dir: string, kitVersion: string): Promise<string> {
  const h = createHash("sha256");
  h.update(`kit:${kitVersion}\n`);
  const walk = async (d: string): Promise<void> => {
    const entries = (await readdir(d, { withFileTypes: true })).sort((a, b) => a.name.localeCompare(b.name));
    for (const e of entries) {
      if (HASH_EXCLUDE.has(e.name)) continue;
      const p = join(d, e.name);
      if (e.isDirectory()) await walk(p);
      else if (e.isFile()) {
        h.update(`${relative(dir, p)}\n`);
        h.update(await readFile(p));
      }
    }
  };
  await walk(dir);
  return h.digest("hex").slice(0, 12);
}

/** The Dockerfile every instance image is built from — generated, never user-authored (ADR-0019).
 * git: the boot reconcile clones onto the source volume in this container (ADR-0004).
 * kubectl: the Sandbox backend shells it against the pod's ServiceAccount (sandbox-kubectl).
 * tsx: in the bundle the kit's `.ts` sources live under node_modules (materialized, not
 * workspace-linked), where Node's own type stripping refuses to run — so the image runs the
 * entrypoint through tsx. An image-runtime detail only; the repo stays zero-build. */
export const INSTANCE_DOCKERFILE = `FROM node:24-slim
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates curl \\
  && curl -fsSLo /usr/local/bin/kubectl "https://dl.k8s.io/release/v1.31.4/bin/linux/$(dpkg --print-architecture)/kubectl" \\
  && chmod +x /usr/local/bin/kubectl \\
  && apt-get purge -y curl && rm -rf /var/lib/apt/lists/* \\
  && npm install -g --no-audit --no-fund tsx@4
WORKDIR /instance
COPY . .
ENV NODE_ENV=production
EXPOSE 4000
CMD ["tsx", "node_modules/@j2/orchestrator/bin/server.ts"]
`;

/** The real build port: pnpm + docker + kind subprocesses. */
export const pnpmDockerBuild: BuildPort = {
  async bundle(instanceDir, outDir) {
    const pkg = JSON.parse(await readFile(join(instanceDir, "package.json"), "utf8")) as { name?: string };
    if (!pkg.name) throw new Error(`${instanceDir}/package.json has no "name" — needed to bundle the instance`);
    // --legacy: materialize (copy) workspace deps into the bundle rather than linking them.
    await exec("pnpm", ["--filter", pkg.name, "--prod", "deploy", "--legacy", outDir], { cwd: instanceDir });
  },

  async build(tag, contextDir) {
    await writeFile(join(contextDir, "Dockerfile"), INSTANCE_DOCKERFILE);
    await exec("docker", ["build", "-t", tag, contextDir], { maxBuffer: 64 * 1024 * 1024 });
  },

  async push(tag) {
    await exec("docker", ["push", tag], { maxBuffer: 64 * 1024 * 1024 });
  },

  async kindLoad(tag, cluster) {
    await exec("kind", ["load", "docker-image", tag, "--name", cluster], { maxBuffer: 64 * 1024 * 1024 });
  },
};

/** Bundle + build under a scratch dir, cleaned up either way. Returns nothing: the image is the
 * side effect, addressed by its tag. */
export async function buildInstanceImage(port: BuildPort, instanceDir: string, tag: string): Promise<void> {
  const out = join(await mkdtemp(join(tmpdir(), "j2-image-")), "bundle");
  try {
    await port.bundle(instanceDir, out);
    await port.build(tag, out);
  } finally {
    await rm(join(out, ".."), { recursive: true, force: true });
  }
}
