// The @kind tier's instance config (ADR-0010): bring-up is the product's own path — one shared
// vanilla kind cluster, locally built kit images, then `j2 up` per scenario into a FRESH namespace
// (`-n` at the CLI; namespace-as-identity makes the scenario the isolation unit, ADR-0019).
//
// `repos[].url` points at the seed git BUNDLE baked into the instance image (`seed/app.bundle`,
// generated by the e2e World when absent): the in-cluster boot reconcile clones it onto the source
// volume — a bundle, because it must be fetchable FROM the cluster and survive the image build
// (`pnpm deploy` strips nested `.git` directories; a single bundle file rides `files` fine).
//
// The image overrides are kit-dev territory (ADR-0019): locally built + `kind load`ed tags
// (`just e2e-kind-up`), including the operator's.

import { defineConfig } from "@j2/orchestrator";

export default defineConfig({
  name: "j2-e2e-kind",
  repos: [{ name: "app", url: "/instance/seed/app.bundle" }],
  // All three images are load-bearing (ADR-0013): the dev Harness runs the scripted persona, the
  // Adapter is the only way that persona can reach its Machine. Without the second, the pod is mute.
  images: { harness: "j2-harness-dev:local", adapter: "j2-adapter:local", operator: "j2-operator:local" },
});
