// The @kind tier's instance config (ADR-0010): bring-up is the product's own path — one shared
// vanilla kind cluster, locally built kit images, then `j2 up` per scenario into a FRESH namespace
// (`-n` at the CLI; namespace-as-identity makes the scenario the isolation unit, ADR-0019).
//
// `repos[].url` points at the seed git BUNDLE baked into the instance image (`seed/app.bundle`,
// generated by the e2e World when absent): the in-cluster boot reconcile clones it onto the source
// volume — a bundle, because it must be fetchable FROM the cluster and survive the image build
// (`pnpm deploy` strips nested `.git` directories; a single bundle file rides `files` fine).
//
// No image is named here (ADR-0038): the `j2` binary under test runs from this checkout, so its
// converge builds the Harness, Adapter, and operator from source at content-addressed tags and
// `kind load`s them itself. Naming a `:local` tag here is exactly the invisible-stale-image bug
// that decision deletes.

import { defineConfig } from "@j2/orchestrator";

export default defineConfig({
  name: "j2-e2e-kind",
  repos: [{ name: "app", url: "/instance/seed/app.bundle" }],
});
